services:
  postgres:
    image: postgres:16-alpine
    container_name: touchlove-postgres
    environment:
      POSTGRES_DB: touchlove_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: touchlove-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: touchlove-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: touchlove-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=touchlove.cdsmemyi00gr.ap-southeast-2.rds.amazonaws.com;Port=5432;Database=postgres;Username=postgres;Password=TouchLove_EXE201
      Redis__ConnectionString: redis:6379
      Email__Host: mailhog
      Email__Port: 1025
      Google__ClientId: ${TOUCHLOVE_GOOGLE_CLIENT_ID}
      Google__ClientSecret: ${TOUCHLOVE_GOOGLE_CLIENT_SECRET}
      Frontend__Url: http://13.236.186.178
      Storage__Provider: S3
      Storage__S3__AccessKey: ""
      Storage__S3__SecretKey: ""
      Storage__S3__Region: ap-southeast-2
      Storage__S3__BucketName: touchlove-bucket
      Storage__S3__PublicUrlTemplate: "https://d3qob24l10t88c.cloudfront.net/{key}"
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - mailhog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://13.236.186.178:5000/api"
    container_name: touchlove-frontend
    ports:
      - "80:3000"
    environment:
      VITE_API_URL: http://13.236.186.178:5000
    depends_on:
      - backend

volumes:
  postgres_data:
