services:
  postgres:
    image: postgres:16-alpine
    container_name: touchlove-postgres
    environment:
      POSTGRES_DB: touchlove_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: touchlove-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: touchlove-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: touchlove-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Redis__ConnectionString: redis:6379
      Email__Host: mailhog
      Email__Port: 1025
      Frontend__Url: https://touchlove.id.vn
      Storage__Provider: S3
      Storage__S3__Region: ap-southeast-2
      Storage__S3__BucketName: touchlove-bucket
      Storage__S3__PublicUrlTemplate: "https://d3qob24l10t88c.cloudfront.net/{key}"
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - mailhog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://api.touchlove.id.vn/api"
    container_name: touchlove-frontend
    ports:
      - "80:3000"
    environment:
      VITE_API_URL: "https://api.touchlove.id.vn/api"
    depends_on:
      - backend

volumes:
  postgres_data:
