CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "AvatarUrl" character varying(500),
        "IsEmailVerified" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "Theme" integer NOT NULL,
        "Language" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "EmailVerificationTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EmailVerificationTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailVerificationTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "MessageTemplates" (
        "Id" uuid NOT NULL,
        "Content" text NOT NULL,
        "Language" character varying(5) NOT NULL DEFAULT 'vi',
        "Category" character varying(100),
        "Status" integer NOT NULL,
        "CreatedByAdminId" uuid NOT NULL,
        "PublishedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_MessageTemplates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MessageTemplates_AspNetUsers_CreatedByAdminId" FOREIGN KEY ("CreatedByAdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByTokenId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "UserSettings" (
        "UserId" uuid NOT NULL,
        "EmailNotifEnabled" boolean NOT NULL,
        "AnnivNotifEnabled" boolean NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserSettings" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_UserSettings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "Couples" (
        "Id" uuid NOT NULL,
        "KeychainAId" uuid NOT NULL,
        "KeychainBId" uuid NOT NULL,
        "CoupleSlug" character varying(100) NOT NULL,
        "CoupleName" character varying(200),
        "StartDate" date NOT NULL,
        "Description" character varying(500),
        "AvatarAUrl" character varying(500),
        "AvatarBUrl" character varying(500),
        "NfcScanCount" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "PairedAt" timestamp with time zone NOT NULL,
        "UnpairedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Couples" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "DailyMessages" (
        "Id" uuid NOT NULL,
        "CoupleId" uuid NOT NULL,
        "TemplateId" uuid,
        "Content" text NOT NULL,
        "MessageDate" date NOT NULL,
        "Source" integer NOT NULL,
        "IsBookmarked" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DailyMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DailyMessages_Couples_CoupleId" FOREIGN KEY ("CoupleId") REFERENCES "Couples" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DailyMessages_MessageTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "MessageTemplates" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "Keychains" (
        "Id" uuid NOT NULL,
        "KeyId" character varying(36) NOT NULL,
        "UserId" uuid,
        "CoupleId" uuid,
        "Status" integer NOT NULL,
        "ActivatedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Keychains" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Keychains_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Keychains_Couples_CoupleId" FOREIGN KEY ("CoupleId") REFERENCES "Couples" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "Memories" (
        "Id" uuid NOT NULL,
        "CoupleId" uuid NOT NULL,
        "UploadedByUserId" uuid NOT NULL,
        "StoragePath" character varying(500) NOT NULL,
        "StorageType" integer NOT NULL,
        "OriginalFileName" character varying(255) NOT NULL,
        "MimeType" character varying(100) NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "Caption" character varying(200),
        "SortOrder" integer NOT NULL,
        "DeleteScheduledAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Memories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Memories_AspNetUsers_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Memories_Couples_CoupleId" FOREIGN KEY ("CoupleId") REFERENCES "Couples" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "NfcScanLogs" (
        "Id" uuid NOT NULL,
        "CoupleId" uuid,
        "KeychainId" uuid NOT NULL,
        "ScannedAt" timestamp with time zone NOT NULL,
        "UserAgent" character varying(500),
        "IpAddress" character varying(45),
        CONSTRAINT "PK_NfcScanLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NfcScanLogs_Couples_CoupleId" FOREIGN KEY ("CoupleId") REFERENCES "Couples" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_NfcScanLogs_Keychains_KeychainId" FOREIGN KEY ("KeychainId") REFERENCES "Keychains" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "PairingInvitations" (
        "Id" uuid NOT NULL,
        "InitiatorKeychainId" uuid NOT NULL,
        "InviteCode" character varying(6) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "UsedByKeychainId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PairingInvitations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PairingInvitations_Keychains_InitiatorKeychainId" FOREIGN KEY ("InitiatorKeychainId") REFERENCES "Keychains" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PairingInvitations_Keychains_UsedByKeychainId" FOREIGN KEY ("UsedByKeychainId") REFERENCES "Keychains" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE TABLE "UnpairRequests" (
        "Id" uuid NOT NULL,
        "CoupleId" uuid NOT NULL,
        "RequestedByKeychainId" uuid NOT NULL,
        "ConfirmedByKeychainId" uuid,
        "IsCompleted" boolean NOT NULL,
        "IsCancelled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UnpairRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UnpairRequests_Couples_CoupleId" FOREIGN KEY ("CoupleId") REFERENCES "Couples" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UnpairRequests_Keychains_ConfirmedByKeychainId" FOREIGN KEY ("ConfirmedByKeychainId") REFERENCES "Keychains" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_UnpairRequests_Keychains_RequestedByKeychainId" FOREIGN KEY ("RequestedByKeychainId") REFERENCES "Keychains" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "IX_Couples_CoupleSlug" ON "Couples" ("CoupleSlug") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Couples_IsActive_IsDeleted" ON "Couples" ("IsActive", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Couples_KeychainAId" ON "Couples" ("KeychainAId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Couples_KeychainBId" ON "Couples" ("KeychainBId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "IX_DailyMessages_CoupleId_MessageDate" ON "DailyMessages" ("CoupleId", "MessageDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_DailyMessages_TemplateId" ON "DailyMessages" ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_EmailVerificationTokens_UserId" ON "EmailVerificationTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Keychains_CoupleId" ON "Keychains" ("CoupleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "IX_Keychains_KeyId" ON "Keychains" ("KeyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Keychains_UserId_IsDeleted" ON "Keychains" ("UserId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Memories_CoupleId_IsDeleted" ON "Memories" ("CoupleId", "IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_Memories_UploadedByUserId" ON "Memories" ("UploadedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_MessageTemplates_CreatedByAdminId" ON "MessageTemplates" ("CreatedByAdminId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_NfcScanLogs_CoupleId" ON "NfcScanLogs" ("CoupleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_NfcScanLogs_KeychainId" ON "NfcScanLogs" ("KeychainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_NfcScanLogs_ScannedAt" ON "NfcScanLogs" ("ScannedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_PairingInvitations_InitiatorKeychainId" ON "PairingInvitations" ("InitiatorKeychainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE UNIQUE INDEX "IX_PairingInvitations_InviteCode" ON "PairingInvitations" ("InviteCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_PairingInvitations_UsedByKeychainId" ON "PairingInvitations" ("UsedByKeychainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_UnpairRequests_ConfirmedByKeychainId" ON "UnpairRequests" ("ConfirmedByKeychainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_UnpairRequests_CoupleId" ON "UnpairRequests" ("CoupleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    CREATE INDEX "IX_UnpairRequests_RequestedByKeychainId" ON "UnpairRequests" ("RequestedByKeychainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    ALTER TABLE "Couples" ADD CONSTRAINT "FK_Couples_Keychains_KeychainAId" FOREIGN KEY ("KeychainAId") REFERENCES "Keychains" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    ALTER TABLE "Couples" ADD CONSTRAINT "FK_Couples_Keychains_KeychainBId" FOREIGN KEY ("KeychainBId") REFERENCES "Keychains" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424144247_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260424144247_Initial', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE TABLE "Orders" (
        "Id" uuid NOT NULL,
        "OrderNumber" character varying(50) NOT NULL,
        "CustomerId" uuid NOT NULL,
        "ShippingFullName" character varying(200) NOT NULL,
        "ShippingPhone" character varying(50) NOT NULL,
        "ShippingAddress" character varying(500) NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" integer NOT NULL,
        "PaymentStatus" integer NOT NULL,
        "PaymentMethod" character varying(100),
        "TransactionId" character varying(200),
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE TABLE "Suppliers" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Phone" character varying(50),
        "Email" character varying(200),
        "Address" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE TABLE "Products" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Slug" character varying(200) NOT NULL,
        "Description" text,
        "Price" numeric(18,2) NOT NULL,
        "StockQuantity" integer NOT NULL,
        "ImageUrls" text,
        "SupplierId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE TABLE "OrderItems" (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426112454_AddEcommerceEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426112454_AddEcommerceEntities', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426131737_Phase8_StoreAndSecurity') THEN
    ALTER TABLE "Products" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426131737_Phase8_StoreAndSecurity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426131737_Phase8_StoreAndSecurity', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527180427_AddCoupleLoveVerification') THEN
    ALTER TABLE "Couples" ADD "IsStartDateConfirmed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527180427_AddCoupleLoveVerification') THEN
    ALTER TABLE "Couples" ADD "ProposedByUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527180427_AddCoupleLoveVerification') THEN
    ALTER TABLE "Couples" ADD "ProposedStartDate" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527180427_AddCoupleLoveVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527180427_AddCoupleLoveVerification', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "Couples" ADD "IsAchievementsPublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "Couples" ADD "IsAlbumPublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "Couples" ADD "IsAnniversariesPublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "Couples" ADD "IsPublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "Bio" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "DateOfBirth" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "Gender" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "IsProfilePublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "NfcPassword" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    ALTER TABLE "AspNetUsers" ADD "UserType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530092525_AddNfcPersonalAndCouplePrivacy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530092525_AddNfcPersonalAndCouplePrivacy', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530104448_AddUserNickname') THEN
    ALTER TABLE "AspNetUsers" ADD "Nickname" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530104448_AddUserNickname') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530104448_AddUserNickname', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530115521_AddAnniversaryRemindersAndMemoryMedia') THEN
    ALTER TABLE "Memories" ADD "AdditionalMediaJson" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530115521_AddAnniversaryRemindersAndMemoryMedia') THEN
    CREATE TABLE "AnniversaryReminders" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Title" text NOT NULL,
        "Date" date NOT NULL,
        "IsRecurring" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_AnniversaryReminders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AnniversaryReminders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530115521_AddAnniversaryRemindersAndMemoryMedia') THEN
    CREATE INDEX "IX_AnniversaryReminders_UserId" ON "AnniversaryReminders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530115521_AddAnniversaryRemindersAndMemoryMedia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530115521_AddAnniversaryRemindersAndMemoryMedia', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530154128_AddPairingConfirmation') THEN
    ALTER TABLE "PairingInvitations" ADD "IsPendingConfirmation" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530154128_AddPairingConfirmation') THEN
    ALTER TABLE "PairingInvitations" ADD "RequestedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530154128_AddPairingConfirmation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530154128_AddPairingConfirmation', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    ALTER TABLE "Products" ADD "CostPrice" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    ALTER TABLE "Products" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    ALTER TABLE "AspNetUsers" ADD "BlockReason" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE TABLE "PendingOrders" (
        "Id" uuid NOT NULL,
        "OrderNumber" character varying(50) NOT NULL,
        "CustomerId" uuid NOT NULL,
        "PayloadJson" text NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "TransactionId" character varying(100) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PendingOrders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PendingOrders_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE TABLE "Vouchers" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "DiscountType" integer NOT NULL,
        "DiscountValue" numeric(18,2) NOT NULL,
        "MaxDiscountCap" numeric(18,2),
        "MinOrderValue" numeric(18,2) NOT NULL,
        "UsageLimitTotal" integer,
        "UsageLimitPerUser" integer NOT NULL,
        "StartAt" timestamp with time zone NOT NULL,
        "EndAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Vouchers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE TABLE "VoucherRedemptions" (
        "Id" uuid NOT NULL,
        "VoucherId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "DiscountApplied" numeric(18,2) NOT NULL,
        "RedeemedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_VoucherRedemptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VoucherRedemptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_VoucherRedemptions_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_VoucherRedemptions_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE INDEX "IX_PendingOrders_CustomerId" ON "PendingOrders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE UNIQUE INDEX "IX_PendingOrders_OrderNumber" ON "PendingOrders" ("OrderNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE UNIQUE INDEX "IX_PendingOrders_TransactionId" ON "PendingOrders" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE INDEX "IX_VoucherRedemptions_OrderId" ON "VoucherRedemptions" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE INDEX "IX_VoucherRedemptions_UserId" ON "VoucherRedemptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE INDEX "IX_VoucherRedemptions_VoucherId" ON "VoucherRedemptions" ("VoucherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    CREATE UNIQUE INDEX "IX_Vouchers_Code" ON "Vouchers" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530184542_AddVoucherAndPendingOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530184542_AddVoucherAndPendingOrder', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531031752_AddAppPolicy') THEN
    CREATE TABLE "AppPolicies" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "Language" text NOT NULL,
        "Content" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_AppPolicies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531031752_AddAppPolicy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260531031752_AddAppPolicy', '10.0.7');
    END IF;
END $EF$;
COMMIT;

